### ISSUE TITLE
Git-seekret version check not working on Ubuntu

### ISSUE THREAD

**Issue by cmc333333** [18F/laptop#141]
The version check in the install script passed despite

```bash
$ git --version
git version 1.9.1
```

Maybe some difference between gnu and bsd awk?

**Comment by mgwalker** [comment]
The current logic for checking versions is:

- if the minor version matches
  - exit true if the patch version is greater/equal to the target patch version
  - exit false if the patch version is less than the target patch version
- if the major version matches
  - exit true if the minor version is greater/equal to the target minor version
  - exit false if the minor version is less than the target minor version
- exit true if the major version is greater/equal to the target major version
- exit false

Where the target version is `2.9.1` and your installed version is `1.9.1`, it exits `true` because the minor versions match and the patch version is greater/equal to the target.  It never evaluates the major version.  It turns out this is a bug in the logic, not a difference with awk.  🙂  Patch incoming.
