### ISSUE TITLE
Enhancement: run command to disable Sketch versioning

### ISSUE THREAD

**Issue by meiqimichelle** [18F/laptop#146]
We've run into a problem with versioning in Sketch on the design team -- see [How Sketch took over 200GB of our MacBooks](https://medium.com/@thomasdegry/how-sketch-took-over-200gb-of-our-macbooks-cb7dd10c8163#.8w9jo7r7q).

Solution:
`defaults write -app ‘sketch’ ApplePersistence -bool no`

Perhaps we should run this by default when folks get their machines set up with the laptop script?

**Comment by mgwalker** [comment]
@jenniferthibault found a way to turn this off in the app's preferences instead of having to use the command line: https://gsa-tts.slack.com/archives/C0488U4H6/p1486667770000019

![screen shot 2017-02-09 at 2 12 41 pm](https://user-images.githubusercontent.com/1775733/50922553-6e0eb280-1410-11e9-9764-1d9acc6fc633.png)

Instead of putting this in the laptop script, it'll be integrated into the design team docs.

As an aside, I'm not sure adding this line to the laptop script would necessarily be effective - if Sketch is not installed when the script runs, the line might not do anything because there's no app to write to yet.
