### ISSUE TITLE
Bundler error

### ISSUE THREAD

**Issue by adampolehonky** [18F/laptop#16]
Hey not sure if it is only affecting me but the script runs fine up until it comes to install/update bundler, I resolved it with manually installing bundler and the script runs fine afterwards with no modifications. Hope this is of some help.

**Comment by monfresh** [comment]
Thanks for the report! Did you by any chance copy the script to your machine before 20:00 (GMT + 1) yesterday? I'm asking because I pushed a fix for this issue yesterday. You can check by opening your local `mac` file and seeing if the first line in the `gem_install_or_update` function looks like this or not:
https://github.com/18F/laptop/blob/master/mac#L89

**Comment by adampolehonky** [comment]
Hi thank you and I have just checked and yes it looks as though I ran the script before your update, I have just removed bundler and then ran the updated script and there were no issues. Thanks.

**Comment by monfresh** [comment]
Awesome! Thanks for confirming.
