### ISSUE TITLE
Why I didn't use these tools

### ISSUE THREAD

**Issue by mxplusb** [18F/laptop#184]
@tbaxter-18f asked me to provide some reasons as to why I didn't use this script for constructive feedback. A lot of my reasons are opinion-based and may or may not be valuable.

* git-seekrets: really out of date and looks to be unmaintained.
* Installs ruby. Nah, I'm good, I'll lazy init on that until I can't anymore, then I'll install rvm, not rbenv. Ruby sucks.
* Installs node via nvm. Nah. Javascript also sucks.
* pyenv-virtualenvwrapper: I prefer Anaconda to venv, all personal preference.
* Installs cloudapp, I don't need it.
* Installs the Selenium chromedriver, also don't need it.
* Installs atom, I use vscode, atom isn't my thing.
* Installs spectacle, not sure what that is, never used it, prolly don't need it.
* Installs ctags, I don't even know the last time I needed ctags because I don't use vim for more than basic editing. I use various symbol servers and language specific LSP implementations (see [LSP](https://langserver.org/)) as it's more abstract.
* Installs tmux, I use screen (only when there's no tab support, which iterm2 has)
* Installs reattach-to-user-namespace, no idea what that is, prolly don't need it.
* Installs coreutils, while useful, can cause scripting problems for local development.
* Doesn't install Go, I need Go for cloud.gov development.
* Doesn't install dotnet core, I need dotnet core for open source dotnet projects.
* Doesn't install Java, I need the AdoptOpenJDK distribution for open source cloud foundry projects.
* Doesn't install [repo](https://gerrit.googlesource.com/git-repo/+/refs/heads/master/README.md), which is a multi-repository manager and would be amazingly helpful for cloud.gov's >50 repos.

I think there are some things that could be very helpful to folks at 18F first coming here:

1. Start using `repo` as the defacto repository manager. It will help with local dev, it's heavily maintained, and it's not going anywhere. Plus it has native code review integrations with Gerrit, which is also very useful. You can have different flavours of repo manifests, which means you can have cloud.gov manifests for cloud.gov code, login.gov manifests for login.gov code, etc.
1. Add more development languages, not just tools.
1. Installation menu, like [`aptitude`](https://help.ubuntu.com/lts/serverguide/aptitude.html.en) or [`buildroot`](https://buildroot.org/), so devs can install recommended categories, but specific tools of their preference.

There might be more reasons I had or improvements I've thought of, those are just the ones that immediately came to mind.

**Comment by tbaxter-18f** [comment]
We'll need to break this apart and determine if laptop is wrong, Mike is wrong :-) or if there really shouldn't be an opinion at all.

I'm also wondering if we should  think about what language(s) we install, when, and by what.

**Comment by bengerman13** [comment]
Could we do this without shaming languages? I don't like writing javascript, but saying it sucks doesn't help this conversation.

**Comment by tbaxter-18f** [comment]
100% agreed. I think the more useful conversation is which languages we're almost certain you'll need here eventually (JS & Python IMO) vs which ones we expect there's a pretty fair chance you'll need (Go & Ruby, IMO) vs which ones you probably don't need buy may wander into sometime for some weird reason (the other ones, IMO :-) )

**Comment by bengerman13** [comment]
Also, RE: git-seekret - the [handbook](https://handbook.18f.gov/sensitive-information/) says we're supposed to have this installed and configured. I don't know if it's in the cloud.gov SSP, but developers should have it installed.
There aren't any recent commits on it, but maybe that's because it Just Works™️?

**Comment by tbaxter-18f** [comment]
Which brings us to the motivation for this issue in the first place:

If our existing opinions are out-of-date or incorrect, I want us to fix them. If we're overly opinionated,  (atom vs code vs whatever, for example) drop the opinion.

For the ones that remain, I'd like it if we could apply the framework outlined in https://github.com/18F/development-guide/pull/83 to those opinions.

**Comment by mxplusb** [comment]
> my reasons are opinion-based and may or may not be valuable

It's my opinion, it may or may not be valuable. I was asked to provide my opinion, I didn't offer it up. If you don't like it or aren't interested in entertaing it, you're more than welcome to close the issue, no hard feelings from me.

In all fairness to this specific project, even if the script met 90-95% of my required uses, I very likely still would not have used it. I'm very peculiar about where things are laid out on disk and what is installed by which manager as that's how I stay organized, regardless of whether it's work or home. I don't even have bootstrapping scripts for myself that meet my desires and goals, so I wouldn't use my reasons for not using this scripts as authoritative.

For me specifically, I would rather have a list of software that is commonly used by the teams, and how I elect to install it is left up to me. It's also important to be aware that I was very close to getting a Windows machine by choice, which wouldn't have worked with this anyways, and a list of software would've been my only hint as to what my options were.

**Comment by tbaxter-18f** [comment]
Mike, I think your opinions are quite valuable -- that's why I asked for them!

**Comment by mgwalker** [comment]
Git-seekret is installed by the laptop script because it's required as a matter of policy for anyone pushing to GIthub. AFAIK, that is an 18F policy, not a TTS one, but I'm not certain about that.  I'd have to dig through Slack to find the original conversations that cemented the decision and I think it's fine to reopen that discussion, but I am also mindful that a lot of thought went into requiring it in the first place.  But you can absolutely install that without the entire laptop script, so that's kind of an aside here.

**Comment by afeld** [comment]
**I strongly recommend we reduce the surface area of the script**, in order to increase usefulness (for people that don't need/want all that configuration) and reduce maintenance burden.

For the fraction of TTS people that use Ruby, for example, do we _really_ care if they use RVM or rbenv or asdf? Also, if they are a Ruby developer, chances are that they have one that they like, or at least know how to use already. In other words, can we slim it down to the things we think 80% of TTS developers? (Developers == anyone that touches the command line.) What would those be? Some things that would qualify:

- XCode command-line tools
- Homebrew
- git-seekrets, or a suitable equivalent. It's 18F policy - the spirit of it is that we protect ourselves from accidentally committing secrets is still very valid.
- Git configuration

> I would rather have a list of software that is commonly used by the teams, and how I elect to install it is left up to me

Yep, the spirit of this is that there is some baseline configuration that we expect for everyone (around Git, specifically), and the rest is recommended. We could make that more clear.

**Comment by afeld** [comment]
As @coreycaitlin pointed out to me, Ruby may not be a great example: we use Jekyll for a lot of our sites, so a lot of people who aren't "Ruby developers" (and thus aren't steeped in Ruby version management) still end up needing Ruby.

**Comment by tbaxter-18f** [comment]
I think if we have strong opinions about something -- even if that opinion is just that we should be consistent -- then it should probably be in the script, and we should be documenting that strong opinion correspondingly. And if we don't have strong opinions 🤷‍♂ 

I do think in a lot of cases you don't _think_ you need something at install time but do later.

**Comment by JJediny** [comment]
The laptop bash of the laptop script is great, but its still bash and many of the packages it defaults to are now either outdated/unwanted without much customization options other than choosing `zsh` over `bash`. 

I think the script would be easier to maintain and more customizable if it were maintained in a configuration management solution over .sh (personal preference being ansible): https://github.com/search?q=ansible+mac

As users would be more likely to edit a standard.config file to add/remove homebrew packages or app store or remote .pkg/.dmg sources. in a yaml file, over a walkthrough shell prompt. 

Some valid points about programming languages setups and their version management solutions are not very well handled with the current script:
 
- [ ] (ruby) currently rbenv over rvm
- [ ] (nodejs) currently a custom mac homebrew of nvm over latest nvm
- [ ] (golang) currently homebrew pinned version of golang over gvm
- [ ] (python) currently python3 w/ virtualenv over pipenv
- [ ] no optional support for .net/java/php/perl

standard desktop apps are missing too:
- [ ] github desktop
- [ ] vscode/atom/sublime
others/etc

**Comment by tbaxter-18f** [comment]
@JJediny remember, many users of this script like it precisely because it does not require them to edit config files. They just want a fast pass to a workable environment so they can get on with their life.

**Comment by mgwalker** [comment]
- AFAIK, Github Desktop is still unapproved - the script used to install it, but we removed it.
- It does install Slack, Chrome, Firefox, Atom, Sublime Text, and VSCode (they're in the Brewfile and Brewfile.local)

Frankly, I think the script is more useful to non-developers, who probably don't have a lot of opinions about rvm or rbenv. But we do want to support all our of designers, strategists, PMs, acq folks, etc. They do a fair bit of code editing as well, so it's helpful if we can streamline getting their environment setup. (I think this compliments @tbaxter-18f's comment.) Thus we install runtimes and runtime version managers for them, and if we've standardized on those things, we can also standardize on instructions for getting projects setup.

(Of course, if we embraced Docker/containers wholesale, that *could* free us up to pick just whatever we want at the project level, but maybe that's a bridge too far.)

**Comment by tbaxter-18f** [comment]
>  if we've standardized on those things, we can also standardize on instructions for getting projects setup.

> (Of course, if we embraced Docker/containers wholesale, that could free us up to pick just whatever we want at the project level, but maybe that's a bridge too far.)

Yup, my opinion (and I recognize the irony here) is that we should avoid personal opinions as much as possible, and that the advantages of standardizing these things and being consistent about them are far greater, especially in a term-limited environment. 

In the past, we've had too many projects that reflected a single persons opinions that had significant long-term maintenance issues just because they differed too much from other projects.

**Comment by afeld** [comment]
Re: GitHub Desktop, see https://github.com/18F/tts-tech-portfolio/issues/24.

**Comment by JJediny** [comment]
Update 7/17/19: We discussed this briefly this morning with @tbaxter-18f @LindsayYoung @afeld. 

~~No one in the near future is going to have time to rewrite the current scripting to any new configuration management language (i.e. ansible/chef/puppet) - so that's out for now.~~

**initial/rough** conscience suggestion: 

A solution cloud be to find a good middleground, to develop two-tiers of the script. Finding the right balance between one script to run it for a barebones baseline dev environment that's needed for good onboarding practices (xcode/git/homebrew/chrome/docker/maybe IDE options - atom/vscode/sublime) vs an optional script opinionated/optional/preferred setup w/ language version control frameworks (e.g. optionally install/setup rvm/nvm/gvm/pipenv). 

This was just a quick chat that we will follow up on - just sharing latest thinking for others to comment/weigh in

**Comment by mogul** [comment]
From @JJediny's post above:
> (python) currently homebrew pinned python3 w/ virtualenv over pyenv/pipenv

We ran into this today... `pyenv-virtualenv` was taking precedence over `pipenv` (used in data.gov development) on my machine leading to difficult-to-diagnose behavior.
Based on that, I agree with @JJediny's idea to split the script here:

> Finding the right balance between one script to run it for a barebones baseline dev environment that's needed for good onboarding practices (xcode/git/homebrew/chrome/docker/maybe IDE options - atom/vscode/sublime) vs an optional script opinionated/preferred setup w/ language version control frameworks (e.g. optionally install/setup rvm/nvm/gvm/pipenv).

**Comment by afeld** [comment]
Moved to more actionable issue: #189. Thanks all!
