### ISSUE TITLE
Script Ending on Image Magick

### ISSUE THREAD

**Issue by lauraGgit** [18F/laptop#43]
The script is ending I think before the whole thing has finished. Below is the relevant portion of my terminal output: 

```Installing imagemagick ...
==> Installing dependencies for imagemagick: libtool, jpeg, libpng, libtiff, freetype
==> Installing imagemagick dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.el_capitan.bottle.tar.gz
==> Pouring libtool-2.4.6.el_capitan.bottle.tar.gz
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:843:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:590:in `link'
/usr/local/Library/Homebrew/formula_installer.rb:450:in `finish'
/usr/local/Library/Homebrew/formula_installer.rb:418:in `install_dependency'
/usr/local/Library/Homebrew/formula_installer.rb:368:in `block in install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:368:in `each'
/usr/local/Library/Homebrew/formula_installer.rb:368:in `install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:175:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:215:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:143:in `<main>'
failed```

**Comment by monfresh** [comment]
Thanks for the report. Based on the log, this is a Homebrew issue. For some reason (no pun intended), Homebrew's `KegOnlyReason` is receiving a `reason` argument equal to `provided_until_xcode43`, and the `valid?` method is checking if `MacOS::Xcode.version < "4.3"`: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_support.rb#L20-L21

The failure is due to `MacOS::Xcode.version` being `nil`.

I would follow the troubleshooting tips on the site mentioned in the logs: https://git.io/brew-troubleshooting, and if that doesn't fix it, I would report the issue to Homebrew here: https://github.com/Homebrew/homebrew/issues

I have not been able to reproduce this on my El Capitan laptop. I uninstalled libtool and imagemagick and was able to reinstall imagemagick without any issues.

Could you please provide more details about the machine you ran this on? Is this a brand new laptop with El Capitan? What specific version? Do you have Xcode installed? Any other dev tools you had on this machine before you ran the script?

**Comment by monfresh** [comment]
I found two Homebrew issues that reported the same `undefined method `<' for nil:NilClass` error, and they were both due to upgrading to El Capitan. Is that what you did? Did you already have Homebrew installed? If so, then please follow the aforementioned Homebrew troubleshooting instructions. If that doesn't work, I'd be happy to sit down with you and fix your machine.

**Comment by monfresh** [comment]
I worked with Laura to fix her setup, and she helped me improve the script. This imagemagick issue was indeed due to a previous Homebrew installation gone bad. I will add a note to the README instructing those who already have Homebrew to make sure it's in working order before running the script.
