### ISSUE TITLE
Jekyll?

### ISSUE THREAD

**Issue by vzvenyach** [18F/laptop#9]
What about `gem install jekyll`. We use it a lot 'round here...

**Comment by monfresh** [comment]
I would say no because jekyll is an app-specific dependency, and it would be the app's responsibility to provide instructions for installing it. The only system-wide gem that `laptop` installs is Bundler, because it is required by any app with a Gemfile.

If you run into a project that depends on jekyll (or any other gem), but doesn't provide installation instructions and an automated installation script, then I would open an issue against that project.

`laptop` is meant to ensure everyone has the same high-level dependencies that certain types of apps require. For example, all Rails apps require Ruby, but then each Rails app has its own set of gems it depends on.

**Comment by vzvenyach** [comment]
Works for me!
